### ISSUE TITLE
EclipseFormatter solved this problem and can work with Save Actions.

### ISSUE THREAD

**Issue by Comee** [eduardp/OCDFormat#6]
[EclipseFormatter](https://github.com/Comee/EclipseFormatter) solved this problem perfectly.

https://github.com/Comee/EclipseFormatter

**Comment by santalucial** [comment]
could you elaborate on how it is solved by EclipseFormatter please? i've spent a couple hours trying to figure it out and i've found nothing suggesting that it's capable of doing what this plugin does

**Comment by Comee** [comment]
I have updated the [README](https://github.com/Comee/EclipseFormatter) file and described how to use it and how it woks.

**Comment by santalucial** [comment]
Thank you, that was helpful, unfortunately i'm not using the exact version of eclipse you built the plugin for, so it prevents the formatter from running alltogheter and since in the office everyone uses different version, your solution, despite being more integrated, is unusable.
